export {default as Hero} from './Hero/Hero'
export {default as Navbar} from './NavBar/Navbar'
export {default as About} from './About/About'
export {default as Contact} from './Contact/Contact'
export {default as CompanyLocation} from './CompanyLocation/CompanyLocation'